import Social from "./Social.js";
import Codepen from "./Codepen.js";
import GitHub from "./Github.js";
import Instagram from "./Instagram.js";
import LinkedIn from "./LinkedIn.js";
import Twitter from "./Twitter.js";
import Medium from "./Medium.js";
import Bar from "./Bar.js";
import Behance from "./Behance.js";
export default Social;
export {Codepen, GitHub, Instagram, LinkedIn, Twitter, Medium, Bar, Behance};
